// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAggregateNamer creates a new instance of MockAggregateNamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregateNamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregateNamer {
	mock := &MockAggregateNamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAggregateNamer is an autogenerated mock type for the AggregateNamer type
type MockAggregateNamer struct {
	mock.Mock
}

type MockAggregateNamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregateNamer) EXPECT() *MockAggregateNamer_Expecter {
	return &MockAggregateNamer_Expecter{mock: &_m.Mock}
}

// AggregateName provides a mock function for the type MockAggregateNamer
func (_mock *MockAggregateNamer) AggregateName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAggregateNamer_AggregateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateName'
type MockAggregateNamer_AggregateName_Call struct {
	*mock.Call
}

// AggregateName is a helper method to define mock.On call
func (_e *MockAggregateNamer_Expecter) AggregateName() *MockAggregateNamer_AggregateName_Call {
	return &MockAggregateNamer_AggregateName_Call{Call: _e.mock.On("AggregateName")}
}

func (_c *MockAggregateNamer_AggregateName_Call) Run(run func()) *MockAggregateNamer_AggregateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateNamer_AggregateName_Call) Return(s string) *MockAggregateNamer_AggregateName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAggregateNamer_AggregateName_Call) RunAndReturn(run func() string) *MockAggregateNamer_AggregateName_Call {
	_c.Call.Return(run)
	return _c
}
