// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAggregateEvent creates a new instance of MockAggregateEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregateEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregateEvent {
	mock := &MockAggregateEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAggregateEvent is an autogenerated mock type for the AggregateEvent type
type MockAggregateEvent struct {
	mock.Mock
}

type MockAggregateEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregateEvent) EXPECT() *MockAggregateEvent_Expecter {
	return &MockAggregateEvent_Expecter{mock: &_m.Mock}
}

// AggregateID provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) AggregateID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAggregateEvent_AggregateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateID'
type MockAggregateEvent_AggregateID_Call struct {
	*mock.Call
}

// AggregateID is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) AggregateID() *MockAggregateEvent_AggregateID_Call {
	return &MockAggregateEvent_AggregateID_Call{Call: _e.mock.On("AggregateID")}
}

func (_c *MockAggregateEvent_AggregateID_Call) Run(run func()) *MockAggregateEvent_AggregateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_AggregateID_Call) Return(s string) *MockAggregateEvent_AggregateID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAggregateEvent_AggregateID_Call) RunAndReturn(run func() string) *MockAggregateEvent_AggregateID_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateName provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) AggregateName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAggregateEvent_AggregateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateName'
type MockAggregateEvent_AggregateName_Call struct {
	*mock.Call
}

// AggregateName is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) AggregateName() *MockAggregateEvent_AggregateName_Call {
	return &MockAggregateEvent_AggregateName_Call{Call: _e.mock.On("AggregateName")}
}

func (_c *MockAggregateEvent_AggregateName_Call) Run(run func()) *MockAggregateEvent_AggregateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_AggregateName_Call) Return(s string) *MockAggregateEvent_AggregateName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAggregateEvent_AggregateName_Call) RunAndReturn(run func() string) *MockAggregateEvent_AggregateName_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateVersion provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) AggregateVersion() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateVersion")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockAggregateEvent_AggregateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateVersion'
type MockAggregateEvent_AggregateVersion_Call struct {
	*mock.Call
}

// AggregateVersion is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) AggregateVersion() *MockAggregateEvent_AggregateVersion_Call {
	return &MockAggregateEvent_AggregateVersion_Call{Call: _e.mock.On("AggregateVersion")}
}

func (_c *MockAggregateEvent_AggregateVersion_Call) Run(run func()) *MockAggregateEvent_AggregateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_AggregateVersion_Call) Return(n int) *MockAggregateEvent_AggregateVersion_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAggregateEvent_AggregateVersion_Call) RunAndReturn(run func() int) *MockAggregateEvent_AggregateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// EventName provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) EventName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAggregateEvent_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockAggregateEvent_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) EventName() *MockAggregateEvent_EventName_Call {
	return &MockAggregateEvent_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockAggregateEvent_EventName_Call) Run(run func()) *MockAggregateEvent_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_EventName_Call) Return(s string) *MockAggregateEvent_EventName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAggregateEvent_EventName_Call) RunAndReturn(run func() string) *MockAggregateEvent_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAggregateEvent_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAggregateEvent_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) ID() *MockAggregateEvent_ID_Call {
	return &MockAggregateEvent_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAggregateEvent_ID_Call) Run(run func()) *MockAggregateEvent_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_ID_Call) Return(s string) *MockAggregateEvent_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAggregateEvent_ID_Call) RunAndReturn(run func() string) *MockAggregateEvent_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) Metadata() Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 Metadata
	if returnFunc, ok := ret.Get(0).(func() Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Metadata)
		}
	}
	return r0
}

// MockAggregateEvent_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockAggregateEvent_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) Metadata() *MockAggregateEvent_Metadata_Call {
	return &MockAggregateEvent_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockAggregateEvent_Metadata_Call) Run(run func()) *MockAggregateEvent_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_Metadata_Call) Return(metadata Metadata) *MockAggregateEvent_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockAggregateEvent_Metadata_Call) RunAndReturn(run func() Metadata) *MockAggregateEvent_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockAggregateEvent_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockAggregateEvent_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) OccurredAt() *MockAggregateEvent_OccurredAt_Call {
	return &MockAggregateEvent_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockAggregateEvent_OccurredAt_Call) Run(run func()) *MockAggregateEvent_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_OccurredAt_Call) Return(time1 time.Time) *MockAggregateEvent_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockAggregateEvent_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockAggregateEvent_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockAggregateEvent
func (_mock *MockAggregateEvent) Payload() EventPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 EventPayload
	if returnFunc, ok := ret.Get(0).(func() EventPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventPayload)
		}
	}
	return r0
}

// MockAggregateEvent_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockAggregateEvent_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockAggregateEvent_Expecter) Payload() *MockAggregateEvent_Payload_Call {
	return &MockAggregateEvent_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockAggregateEvent_Payload_Call) Run(run func()) *MockAggregateEvent_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregateEvent_Payload_Call) Return(eventPayload EventPayload) *MockAggregateEvent_Payload_Call {
	_c.Call.Return(eventPayload)
	return _c
}

func (_c *MockAggregateEvent_Payload_Call) RunAndReturn(run func() EventPayload) *MockAggregateEvent_Payload_Call {
	_c.Call.Return(run)
	return _c
}
