// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPayload creates a new instance of MockEventPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPayload {
	mock := &MockEventPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPayload is an autogenerated mock type for the EventPayload type
type MockEventPayload struct {
	mock.Mock
}

type MockEventPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPayload) EXPECT() *MockEventPayload_Expecter {
	return &MockEventPayload_Expecter{mock: &_m.Mock}
}
