// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventSubscriber creates a new instance of MockEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriber[T Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriber[T] {
	mock := &MockEventSubscriber[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSubscriber is an autogenerated mock type for the EventSubscriber type
type MockEventSubscriber[T Event] struct {
	mock.Mock
}

type MockEventSubscriber_Expecter[T Event] struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriber[T]) EXPECT() *MockEventSubscriber_Expecter[T] {
	return &MockEventSubscriber_Expecter[T]{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockEventSubscriber
func (_mock *MockEventSubscriber[T]) Subscribe(name string, handler EventHandler[T]) {
	_mock.Called(name, handler)
	return
}

// MockEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventSubscriber_Subscribe_Call[T Event] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - name string
//   - handler EventHandler[T]
func (_e *MockEventSubscriber_Expecter[T]) Subscribe(name interface{}, handler interface{}) *MockEventSubscriber_Subscribe_Call[T] {
	return &MockEventSubscriber_Subscribe_Call[T]{Call: _e.mock.On("Subscribe", name, handler)}
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) Run(run func(name string, handler EventHandler[T])) *MockEventSubscriber_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 EventHandler[T]
		if args[1] != nil {
			arg1 = args[1].(EventHandler[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) Return() *MockEventSubscriber_Subscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) RunAndReturn(run func(name string, handler EventHandler[T])) *MockEventSubscriber_Subscribe_Call[T] {
	_c.Run(run)
	return _c
}
