// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventsSetter creates a new instance of MockEventsSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventsSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventsSetter {
	mock := &MockEventsSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventsSetter is an autogenerated mock type for the EventsSetter type
type MockEventsSetter struct {
	mock.Mock
}

type MockEventsSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventsSetter) EXPECT() *MockEventsSetter_Expecter {
	return &MockEventsSetter_Expecter{mock: &_m.Mock}
}

// setEvents provides a mock function for the type MockEventsSetter
func (_mock *MockEventsSetter) setEvents(events []Event) {
	_mock.Called(events)
	return
}

// MockEventsSetter_setEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setEvents'
type MockEventsSetter_setEvents_Call struct {
	*mock.Call
}

// setEvents is a helper method to define mock.On call
//   - events []Event
func (_e *MockEventsSetter_Expecter) setEvents(events interface{}) *MockEventsSetter_setEvents_Call {
	return &MockEventsSetter_setEvents_Call{Call: _e.mock.On("setEvents", events)}
}

func (_c *MockEventsSetter_setEvents_Call) Run(run func(events []Event)) *MockEventsSetter_setEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Event
		if args[0] != nil {
			arg0 = args[0].([]Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventsSetter_setEvents_Call) Return() *MockEventsSetter_setEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventsSetter_setEvents_Call) RunAndReturn(run func(events []Event)) *MockEventsSetter_setEvents_Call {
	_c.Run(run)
	return _c
}
