// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventHandler creates a new instance of MockEventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventHandler[T Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventHandler[T] {
	mock := &MockEventHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventHandler is an autogenerated mock type for the EventHandler type
type MockEventHandler[T Event] struct {
	mock.Mock
}

type MockEventHandler_Expecter[T Event] struct {
	mock *mock.Mock
}

func (_m *MockEventHandler[T]) EXPECT() *MockEventHandler_Expecter[T] {
	return &MockEventHandler_Expecter[T]{mock: &_m.Mock}
}

// HandleEvent provides a mock function for the type MockEventHandler
func (_mock *MockEventHandler[T]) HandleEvent(ctx context.Context, event T) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventHandler_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type MockEventHandler_HandleEvent_Call[T Event] struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *MockEventHandler_Expecter[T]) HandleEvent(ctx interface{}, event interface{}) *MockEventHandler_HandleEvent_Call[T] {
	return &MockEventHandler_HandleEvent_Call[T]{Call: _e.mock.On("HandleEvent", ctx, event)}
}

func (_c *MockEventHandler_HandleEvent_Call[T]) Run(run func(ctx context.Context, event T)) *MockEventHandler_HandleEvent_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventHandler_HandleEvent_Call[T]) Return(err error) *MockEventHandler_HandleEvent_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventHandler_HandleEvent_Call[T]) RunAndReturn(run func(ctx context.Context, event T) error) *MockEventHandler_HandleEvent_Call[T] {
	_c.Call.Return(run)
	return _c
}
