// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventer creates a new instance of MockEventer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventer {
	mock := &MockEventer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventer is an autogenerated mock type for the Eventer type
type MockEventer struct {
	mock.Mock
}

type MockEventer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventer) EXPECT() *MockEventer_Expecter {
	return &MockEventer_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function for the type MockEventer
func (_mock *MockEventer) AddEvent(s string, eventPayload EventPayload, eventOptions ...EventOption) {
	if len(eventOptions) > 0 {
		_mock.Called(s, eventPayload, eventOptions)
	} else {
		_mock.Called(s, eventPayload)
	}

	return
}

// MockEventer_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type MockEventer_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - s string
//   - eventPayload EventPayload
//   - eventOptions ...EventOption
func (_e *MockEventer_Expecter) AddEvent(s interface{}, eventPayload interface{}, eventOptions ...interface{}) *MockEventer_AddEvent_Call {
	return &MockEventer_AddEvent_Call{Call: _e.mock.On("AddEvent",
		append([]interface{}{s, eventPayload}, eventOptions...)...)}
}

func (_c *MockEventer_AddEvent_Call) Run(run func(s string, eventPayload EventPayload, eventOptions ...EventOption)) *MockEventer_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 EventPayload
		if args[1] != nil {
			arg1 = args[1].(EventPayload)
		}
		var arg2 []EventOption
		var variadicArgs []EventOption
		if len(args) > 2 {
			variadicArgs = args[2].([]EventOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEventer_AddEvent_Call) Return() *MockEventer_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventer_AddEvent_Call) RunAndReturn(run func(s string, eventPayload EventPayload, eventOptions ...EventOption)) *MockEventer_AddEvent_Call {
	_c.Run(run)
	return _c
}

// ClearEvents provides a mock function for the type MockEventer
func (_mock *MockEventer) ClearEvents() {
	_mock.Called()
	return
}

// MockEventer_ClearEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearEvents'
type MockEventer_ClearEvents_Call struct {
	*mock.Call
}

// ClearEvents is a helper method to define mock.On call
func (_e *MockEventer_Expecter) ClearEvents() *MockEventer_ClearEvents_Call {
	return &MockEventer_ClearEvents_Call{Call: _e.mock.On("ClearEvents")}
}

func (_c *MockEventer_ClearEvents_Call) Run(run func()) *MockEventer_ClearEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventer_ClearEvents_Call) Return() *MockEventer_ClearEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventer_ClearEvents_Call) RunAndReturn(run func()) *MockEventer_ClearEvents_Call {
	_c.Run(run)
	return _c
}

// Events provides a mock function for the type MockEventer
func (_mock *MockEventer) Events() []AggregateEvent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []AggregateEvent
	if returnFunc, ok := ret.Get(0).(func() []AggregateEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AggregateEvent)
		}
	}
	return r0
}

// MockEventer_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockEventer_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *MockEventer_Expecter) Events() *MockEventer_Events_Call {
	return &MockEventer_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *MockEventer_Events_Call) Run(run func()) *MockEventer_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventer_Events_Call) Return(aggregateEvents []AggregateEvent) *MockEventer_Events_Call {
	_c.Call.Return(aggregateEvents)
	return _c
}

func (_c *MockEventer_Events_Call) RunAndReturn(run func() []AggregateEvent) *MockEventer_Events_Call {
	_c.Call.Return(run)
	return _c
}
