// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher[T Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher[T] {
	mock := &MockEventPublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher[T Event] struct {
	mock.Mock
}

type MockEventPublisher_Expecter[T Event] struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher[T]) EXPECT() *MockEventPublisher_Expecter[T] {
	return &MockEventPublisher_Expecter[T]{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher[T]) Publish(ctx context.Context, events ...T) error {
	var tmpRet mock.Arguments
	if len(events) > 0 {
		tmpRet = _mock.Called(ctx, events)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...T) error); ok {
		r0 = returnFunc(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call[T Event] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...T
func (_e *MockEventPublisher_Expecter[T]) Publish(ctx interface{}, events ...interface{}) *MockEventPublisher_Publish_Call[T] {
	return &MockEventPublisher_Publish_Call[T]{Call: _e.mock.On("Publish",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *MockEventPublisher_Publish_Call[T]) Run(run func(ctx context.Context, events ...T)) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []T
		var variadicArgs []T
		if len(args) > 1 {
			variadicArgs = args[1].([]T)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call[T]) Return(err error) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call[T]) RunAndReturn(run func(ctx context.Context, events ...T) error) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Return(run)
	return _c
}
