// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventOption creates a new instance of MockEventOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventOption {
	mock := &MockEventOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventOption is an autogenerated mock type for the EventOption type
type MockEventOption struct {
	mock.Mock
}

type MockEventOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventOption) EXPECT() *MockEventOption_Expecter {
	return &MockEventOption_Expecter{mock: &_m.Mock}
}

// configureEvent provides a mock function for the type MockEventOption
func (_mock *MockEventOption) configureEvent(eventMoqParam *event) {
	_mock.Called(eventMoqParam)
	return
}

// MockEventOption_configureEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'configureEvent'
type MockEventOption_configureEvent_Call struct {
	*mock.Call
}

// configureEvent is a helper method to define mock.On call
//   - eventMoqParam *event
func (_e *MockEventOption_Expecter) configureEvent(eventMoqParam interface{}) *MockEventOption_configureEvent_Call {
	return &MockEventOption_configureEvent_Call{Call: _e.mock.On("configureEvent", eventMoqParam)}
}

func (_c *MockEventOption_configureEvent_Call) Run(run func(eventMoqParam *event)) *MockEventOption_configureEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *event
		if args[0] != nil {
			arg0 = args[0].(*event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventOption_configureEvent_Call) Return() *MockEventOption_configureEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventOption_configureEvent_Call) RunAndReturn(run func(eventMoqParam *event)) *MockEventOption_configureEvent_Call {
	_c.Run(run)
	return _c
}
