// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// EventName provides a mock function for the type MockEvent
func (_mock *MockEvent) EventName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockEvent_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockEvent_Expecter) EventName() *MockEvent_EventName_Call {
	return &MockEvent_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockEvent_EventName_Call) Run(run func()) *MockEvent_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_EventName_Call) Return(s string) *MockEvent_EventName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_EventName_Call) RunAndReturn(run func() string) *MockEvent_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEvent
func (_mock *MockEvent) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvent_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEvent_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEvent_Expecter) ID() *MockEvent_ID_Call {
	return &MockEvent_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEvent_ID_Call) Run(run func()) *MockEvent_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_ID_Call) Return(s string) *MockEvent_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvent_ID_Call) RunAndReturn(run func() string) *MockEvent_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockEvent
func (_mock *MockEvent) Metadata() Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 Metadata
	if returnFunc, ok := ret.Get(0).(func() Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Metadata)
		}
	}
	return r0
}

// MockEvent_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockEvent_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Metadata() *MockEvent_Metadata_Call {
	return &MockEvent_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockEvent_Metadata_Call) Run(run func()) *MockEvent_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Metadata_Call) Return(metadata Metadata) *MockEvent_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockEvent_Metadata_Call) RunAndReturn(run func() Metadata) *MockEvent_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockEvent
func (_mock *MockEvent) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEvent_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockEvent_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockEvent_Expecter) OccurredAt() *MockEvent_OccurredAt_Call {
	return &MockEvent_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockEvent_OccurredAt_Call) Run(run func()) *MockEvent_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_OccurredAt_Call) Return(time1 time.Time) *MockEvent_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEvent_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockEvent_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockEvent
func (_mock *MockEvent) Payload() EventPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 EventPayload
	if returnFunc, ok := ret.Get(0).(func() EventPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventPayload)
		}
	}
	return r0
}

// MockEvent_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockEvent_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockEvent_Expecter) Payload() *MockEvent_Payload_Call {
	return &MockEvent_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockEvent_Payload_Call) Run(run func()) *MockEvent_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_Payload_Call) Return(eventPayload EventPayload) *MockEvent_Payload_Call {
	_c.Call.Return(eventPayload)
	return _c
}

func (_c *MockEvent_Payload_Call) RunAndReturn(run func() EventPayload) *MockEvent_Payload_Call {
	_c.Call.Return(run)
	return _c
}
