// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIDSetter creates a new instance of MockIDSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDSetter {
	mock := &MockIDSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDSetter is an autogenerated mock type for the IDSetter type
type MockIDSetter struct {
	mock.Mock
}

type MockIDSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDSetter) EXPECT() *MockIDSetter_Expecter {
	return &MockIDSetter_Expecter{mock: &_m.Mock}
}

// setID provides a mock function for the type MockIDSetter
func (_mock *MockIDSetter) setID(s string) {
	_mock.Called(s)
	return
}

// MockIDSetter_setID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setID'
type MockIDSetter_setID_Call struct {
	*mock.Call
}

// setID is a helper method to define mock.On call
//   - s string
func (_e *MockIDSetter_Expecter) setID(s interface{}) *MockIDSetter_setID_Call {
	return &MockIDSetter_setID_Call{Call: _e.mock.On("setID", s)}
}

func (_c *MockIDSetter_setID_Call) Run(run func(s string)) *MockIDSetter_setID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDSetter_setID_Call) Return() *MockIDSetter_setID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIDSetter_setID_Call) RunAndReturn(run func(s string)) *MockIDSetter_setID_Call {
	_c.Run(run)
	return _c
}
