// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNameSetter creates a new instance of MockNameSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNameSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNameSetter {
	mock := &MockNameSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNameSetter is an autogenerated mock type for the NameSetter type
type MockNameSetter struct {
	mock.Mock
}

type MockNameSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNameSetter) EXPECT() *MockNameSetter_Expecter {
	return &MockNameSetter_Expecter{mock: &_m.Mock}
}

// setName provides a mock function for the type MockNameSetter
func (_mock *MockNameSetter) setName(s string) {
	_mock.Called(s)
	return
}

// MockNameSetter_setName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setName'
type MockNameSetter_setName_Call struct {
	*mock.Call
}

// setName is a helper method to define mock.On call
//   - s string
func (_e *MockNameSetter_Expecter) setName(s interface{}) *MockNameSetter_setName_Call {
	return &MockNameSetter_setName_Call{Call: _e.mock.On("setName", s)}
}

func (_c *MockNameSetter_setName_Call) Run(run func(s string)) *MockNameSetter_setName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNameSetter_setName_Call) Return() *MockNameSetter_setName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNameSetter_setName_Call) RunAndReturn(run func(s string)) *MockNameSetter_setName_Call {
	_c.Run(run)
	return _c
}
