// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messaging

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageProcessor creates a new instance of MockMessageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageProcessor {
	mock := &MockMessageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageProcessor is an autogenerated mock type for the MessageProcessor type
type MockMessageProcessor struct {
	mock.Mock
}

type MockMessageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageProcessor) EXPECT() *MockMessageProcessor_Expecter {
	return &MockMessageProcessor_Expecter{mock: &_m.Mock}
}

// ProcessMessage provides a mock function for the type MockMessageProcessor
func (_mock *MockMessageProcessor) ProcessMessage(message any) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageProcessor_ProcessMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMessage'
type MockMessageProcessor_ProcessMessage_Call struct {
	*mock.Call
}

// ProcessMessage is a helper method to define mock.On call
//   - message any
func (_e *MockMessageProcessor_Expecter) ProcessMessage(message interface{}) *MockMessageProcessor_ProcessMessage_Call {
	return &MockMessageProcessor_ProcessMessage_Call{Call: _e.mock.On("ProcessMessage", message)}
}

func (_c *MockMessageProcessor_ProcessMessage_Call) Run(run func(message any)) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageProcessor_ProcessMessage_Call) Return(err error) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageProcessor_ProcessMessage_Call) RunAndReturn(run func(message any) error) *MockMessageProcessor_ProcessMessage_Call {
	_c.Call.Return(run)
	return _c
}
