// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messaging

import (
	"context"

	"github.com/racibaz/go-arch/internal/modules/post/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostMessagePublisher creates a new instance of MockPostMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostMessagePublisher {
	mock := &MockPostMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostMessagePublisher is an autogenerated mock type for the PostMessagePublisher type
type MockPostMessagePublisher struct {
	mock.Mock
}

type MockPostMessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostMessagePublisher) EXPECT() *MockPostMessagePublisher_Expecter {
	return &MockPostMessagePublisher_Expecter{mock: &_m.Mock}
}

// PublishPostCreated provides a mock function for the type MockPostMessagePublisher
func (_mock *MockPostMessagePublisher) PublishPostCreated(ctx context.Context, payload *domain.Post) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishPostCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostMessagePublisher_PublishPostCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishPostCreated'
type MockPostMessagePublisher_PublishPostCreated_Call struct {
	*mock.Call
}

// PublishPostCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *domain.Post
func (_e *MockPostMessagePublisher_Expecter) PublishPostCreated(ctx interface{}, payload interface{}) *MockPostMessagePublisher_PublishPostCreated_Call {
	return &MockPostMessagePublisher_PublishPostCreated_Call{Call: _e.mock.On("PublishPostCreated", ctx, payload)}
}

func (_c *MockPostMessagePublisher_PublishPostCreated_Call) Run(run func(ctx context.Context, payload *domain.Post)) *MockPostMessagePublisher_PublishPostCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostMessagePublisher_PublishPostCreated_Call) Return(err error) *MockPostMessagePublisher_PublishPostCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostMessagePublisher_PublishPostCreated_Call) RunAndReturn(run func(ctx context.Context, payload *domain.Post) error) *MockPostMessagePublisher_PublishPostCreated_Call {
	_c.Call.Return(run)
	return _c
}
