// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messaging

import (
	"context"

	"github.com/racibaz/go-arch/internal/modules/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserMessagePublisher creates a new instance of MockUserMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserMessagePublisher {
	mock := &MockUserMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserMessagePublisher is an autogenerated mock type for the UserMessagePublisher type
type MockUserMessagePublisher struct {
	mock.Mock
}

type MockUserMessagePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserMessagePublisher) EXPECT() *MockUserMessagePublisher_Expecter {
	return &MockUserMessagePublisher_Expecter{mock: &_m.Mock}
}

// PublishUserLoggedIn provides a mock function for the type MockUserMessagePublisher
func (_mock *MockUserMessagePublisher) PublishUserLoggedIn(ctx context.Context, payload *domain.User) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserLoggedIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserMessagePublisher_PublishUserLoggedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLoggedIn'
type MockUserMessagePublisher_PublishUserLoggedIn_Call struct {
	*mock.Call
}

// PublishUserLoggedIn is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *domain.User
func (_e *MockUserMessagePublisher_Expecter) PublishUserLoggedIn(ctx interface{}, payload interface{}) *MockUserMessagePublisher_PublishUserLoggedIn_Call {
	return &MockUserMessagePublisher_PublishUserLoggedIn_Call{Call: _e.mock.On("PublishUserLoggedIn", ctx, payload)}
}

func (_c *MockUserMessagePublisher_PublishUserLoggedIn_Call) Run(run func(ctx context.Context, payload *domain.User)) *MockUserMessagePublisher_PublishUserLoggedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserLoggedIn_Call) Return(err error) *MockUserMessagePublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserLoggedIn_Call) RunAndReturn(run func(ctx context.Context, payload *domain.User) error) *MockUserMessagePublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserLoggedOut provides a mock function for the type MockUserMessagePublisher
func (_mock *MockUserMessagePublisher) PublishUserLoggedOut(ctx context.Context, payload *domain.User) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserLoggedOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserMessagePublisher_PublishUserLoggedOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLoggedOut'
type MockUserMessagePublisher_PublishUserLoggedOut_Call struct {
	*mock.Call
}

// PublishUserLoggedOut is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *domain.User
func (_e *MockUserMessagePublisher_Expecter) PublishUserLoggedOut(ctx interface{}, payload interface{}) *MockUserMessagePublisher_PublishUserLoggedOut_Call {
	return &MockUserMessagePublisher_PublishUserLoggedOut_Call{Call: _e.mock.On("PublishUserLoggedOut", ctx, payload)}
}

func (_c *MockUserMessagePublisher_PublishUserLoggedOut_Call) Run(run func(ctx context.Context, payload *domain.User)) *MockUserMessagePublisher_PublishUserLoggedOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserLoggedOut_Call) Return(err error) *MockUserMessagePublisher_PublishUserLoggedOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserLoggedOut_Call) RunAndReturn(run func(ctx context.Context, payload *domain.User) error) *MockUserMessagePublisher_PublishUserLoggedOut_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserRegistered provides a mock function for the type MockUserMessagePublisher
func (_mock *MockUserMessagePublisher) PublishUserRegistered(ctx context.Context, payload *domain.User) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserRegistered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserMessagePublisher_PublishUserRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserRegistered'
type MockUserMessagePublisher_PublishUserRegistered_Call struct {
	*mock.Call
}

// PublishUserRegistered is a helper method to define mock.On call
//   - ctx context.Context
//   - payload *domain.User
func (_e *MockUserMessagePublisher_Expecter) PublishUserRegistered(ctx interface{}, payload interface{}) *MockUserMessagePublisher_PublishUserRegistered_Call {
	return &MockUserMessagePublisher_PublishUserRegistered_Call{Call: _e.mock.On("PublishUserRegistered", ctx, payload)}
}

func (_c *MockUserMessagePublisher_PublishUserRegistered_Call) Run(run func(ctx context.Context, payload *domain.User)) *MockUserMessagePublisher_PublishUserRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserRegistered_Call) Return(err error) *MockUserMessagePublisher_PublishUserRegistered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserMessagePublisher_PublishUserRegistered_Call) RunAndReturn(run func(ctx context.Context, payload *domain.User) error) *MockUserMessagePublisher_PublishUserRegistered_Call {
	_c.Call.Return(run)
	return _c
}
