// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryHandler creates a new instance of MockQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryHandler[Q any, R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryHandler[Q, R] {
	mock := &MockQueryHandler[Q, R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryHandler is an autogenerated mock type for the QueryHandler type
type MockQueryHandler[Q any, R any] struct {
	mock.Mock
}

type MockQueryHandler_Expecter[Q any, R any] struct {
	mock *mock.Mock
}

func (_m *MockQueryHandler[Q, R]) EXPECT() *MockQueryHandler_Expecter[Q, R] {
	return &MockQueryHandler_Expecter[Q, R]{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockQueryHandler
func (_mock *MockQueryHandler[Q, R]) Handle(ctx context.Context, query Q) (R, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Q) (R, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Q) R); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Q) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockQueryHandler_Handle_Call[Q any, R any] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - query Q
func (_e *MockQueryHandler_Expecter[Q, R]) Handle(ctx interface{}, query interface{}) *MockQueryHandler_Handle_Call[Q, R] {
	return &MockQueryHandler_Handle_Call[Q, R]{Call: _e.mock.On("Handle", ctx, query)}
}

func (_c *MockQueryHandler_Handle_Call[Q, R]) Run(run func(ctx context.Context, query Q)) *MockQueryHandler_Handle_Call[Q, R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Q
		if args[1] != nil {
			arg1 = args[1].(Q)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryHandler_Handle_Call[Q, R]) Return(v R, err error) *MockQueryHandler_Handle_Call[Q, R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockQueryHandler_Handle_Call[Q, R]) RunAndReturn(run func(ctx context.Context, query Q) (R, error)) *MockQueryHandler_Handle_Call[Q, R] {
	_c.Call.Return(run)
	return _c
}
