// Package openapi_spec Code generated by swaggo/swag. DO NOT EDIT
package openapi_spec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "do health check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts": {
            "post": {
                "description": "It is a method to create a new post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "post store",
                "parameters": [
                    {
                        "description": "Create Post Request DTO",
                        "name": "post",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreatePostRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Post created successfully",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreatePostResponseDto"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/errors.appError"
                        }
                    },
                    "422": {
                        "description": "Post validation request body does not validate",
                        "schema": {
                            "$ref": "#/definitions/errors.appError"
                        }
                    },
                    "500": {
                        "description": "Post create failed",
                        "schema": {
                            "$ref": "#/definitions/errors.appError"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "It is a method to retrieve a post by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get post by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Post ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Post retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/github_com_racibaz_go-arch_internal_modules_post_features_gettingpostbyid_v1_adapters_endpoints_dtos.GetPostResponseDto"
                        }
                    },
                    "400": {
                        "description": "The Id does not parse correctly",
                        "schema": {
                            "$ref": "#/definitions/errors.appError"
                        }
                    },
                    "404": {
                        "description": "Page not found",
                        "schema": {
                            "$ref": "#/definitions/errors.appError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreatePostRequestDto": {
            "description": "CreatePostRequestDto is a data transfer object for creating a post",
            "type": "object",
            "required": [
                "content",
                "description",
                "title",
                "user_id"
            ],
            "properties": {
                "content": {
                    "description": "@Description\tContent is the content of the post",
                    "type": "string",
                    "minLength": 10
                },
                "description": {
                    "description": "@Description\tDescription is the description of the post",
                    "type": "string",
                    "minLength": 10
                },
                "title": {
                    "description": "@Description\tTitle is the title of the post",
                    "type": "string",
                    "minLength": 10
                },
                "user_id": {
                    "description": "@Description\tUserId is the ID of the user creating the post",
                    "type": "string"
                }
            }
        },
        "dtos.CreatePostResponseDto": {
            "description": "CreatePostResponseDto is a data transfer object for reporting the details of a created post",
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/github_com_racibaz_go-arch_internal_modules_post_features_creatingpost_v1_application_dtos.Post"
                }
            }
        },
        "errors.appError": {
            "type": "object",
            "properties": {
                "cause": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_racibaz_go-arch_internal_modules_post_features_creatingpost_v1_application_dtos.Post": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "@Description\tContent is the content of the post",
                    "type": "string"
                },
                "description": {
                    "description": "@Description\tDescription is the description of the post",
                    "type": "string"
                },
                "status": {
                    "description": "@Description\tStatus is the status of the post",
                    "type": "string"
                },
                "title": {
                    "description": "@Description\tTitle is the title of the post",
                    "type": "string"
                }
            }
        },
        "github_com_racibaz_go-arch_internal_modules_post_features_gettingpostbyid_v1_adapters_endpoints_dtos.GetPostResponseDto": {
            "description": "GetPostResponseDto is a data transfer object for reporting the details of a post",
            "type": "object",
            "properties": {
                "post": {
                    "$ref": "#/definitions/github_com_racibaz_go-arch_internal_modules_post_features_gettingpostbyid_v1_adapters_endpoints_dtos.Post"
                }
            }
        },
        "github_com_racibaz_go-arch_internal_modules_post_features_gettingpostbyid_v1_adapters_endpoints_dtos.Post": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "@Description\tContent is the content of the post",
                    "type": "string"
                },
                "description": {
                    "description": "@Description\tDescription is the description of the post",
                    "type": "string"
                },
                "status": {
                    "description": "@Description\tStatus is the status of the post",
                    "type": "string"
                },
                "title": {
                    "description": "@Description\tTitle is the title of the post",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
