// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/racibaz/go-arch/pkg/ddd"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDomainEventHandlers creates a new instance of MockDomainEventHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainEventHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainEventHandlers {
	mock := &MockDomainEventHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDomainEventHandlers is an autogenerated mock type for the DomainEventHandlers type
type MockDomainEventHandlers struct {
	mock.Mock
}

type MockDomainEventHandlers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainEventHandlers) EXPECT() *MockDomainEventHandlers_Expecter {
	return &MockDomainEventHandlers_Expecter{mock: &_m.Mock}
}

// OnPostCanceled provides a mock function for the type MockDomainEventHandlers
func (_mock *MockDomainEventHandlers) OnPostCanceled(ctx context.Context, event ddd.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for OnPostCanceled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ddd.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainEventHandlers_OnPostCanceled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPostCanceled'
type MockDomainEventHandlers_OnPostCanceled_Call struct {
	*mock.Call
}

// OnPostCanceled is a helper method to define mock.On call
//   - ctx context.Context
//   - event ddd.Event
func (_e *MockDomainEventHandlers_Expecter) OnPostCanceled(ctx interface{}, event interface{}) *MockDomainEventHandlers_OnPostCanceled_Call {
	return &MockDomainEventHandlers_OnPostCanceled_Call{Call: _e.mock.On("OnPostCanceled", ctx, event)}
}

func (_c *MockDomainEventHandlers_OnPostCanceled_Call) Run(run func(ctx context.Context, event ddd.Event)) *MockDomainEventHandlers_OnPostCanceled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ddd.Event
		if args[1] != nil {
			arg1 = args[1].(ddd.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCanceled_Call) Return(err error) *MockDomainEventHandlers_OnPostCanceled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCanceled_Call) RunAndReturn(run func(ctx context.Context, event ddd.Event) error) *MockDomainEventHandlers_OnPostCanceled_Call {
	_c.Call.Return(run)
	return _c
}

// OnPostCompleted provides a mock function for the type MockDomainEventHandlers
func (_mock *MockDomainEventHandlers) OnPostCompleted(ctx context.Context, event ddd.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for OnPostCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ddd.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainEventHandlers_OnPostCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPostCompleted'
type MockDomainEventHandlers_OnPostCompleted_Call struct {
	*mock.Call
}

// OnPostCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - event ddd.Event
func (_e *MockDomainEventHandlers_Expecter) OnPostCompleted(ctx interface{}, event interface{}) *MockDomainEventHandlers_OnPostCompleted_Call {
	return &MockDomainEventHandlers_OnPostCompleted_Call{Call: _e.mock.On("OnPostCompleted", ctx, event)}
}

func (_c *MockDomainEventHandlers_OnPostCompleted_Call) Run(run func(ctx context.Context, event ddd.Event)) *MockDomainEventHandlers_OnPostCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ddd.Event
		if args[1] != nil {
			arg1 = args[1].(ddd.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCompleted_Call) Return(err error) *MockDomainEventHandlers_OnPostCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCompleted_Call) RunAndReturn(run func(ctx context.Context, event ddd.Event) error) *MockDomainEventHandlers_OnPostCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// OnPostCreated provides a mock function for the type MockDomainEventHandlers
func (_mock *MockDomainEventHandlers) OnPostCreated(ctx context.Context, event ddd.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for OnPostCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ddd.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainEventHandlers_OnPostCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPostCreated'
type MockDomainEventHandlers_OnPostCreated_Call struct {
	*mock.Call
}

// OnPostCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - event ddd.Event
func (_e *MockDomainEventHandlers_Expecter) OnPostCreated(ctx interface{}, event interface{}) *MockDomainEventHandlers_OnPostCreated_Call {
	return &MockDomainEventHandlers_OnPostCreated_Call{Call: _e.mock.On("OnPostCreated", ctx, event)}
}

func (_c *MockDomainEventHandlers_OnPostCreated_Call) Run(run func(ctx context.Context, event ddd.Event)) *MockDomainEventHandlers_OnPostCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ddd.Event
		if args[1] != nil {
			arg1 = args[1].(ddd.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCreated_Call) Return(err error) *MockDomainEventHandlers_OnPostCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainEventHandlers_OnPostCreated_Call) RunAndReturn(run func(ctx context.Context, event ddd.Event) error) *MockDomainEventHandlers_OnPostCreated_Call {
	_c.Call.Return(run)
	return _c
}

// OnPostReadied provides a mock function for the type MockDomainEventHandlers
func (_mock *MockDomainEventHandlers) OnPostReadied(ctx context.Context, event ddd.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for OnPostReadied")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ddd.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainEventHandlers_OnPostReadied_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPostReadied'
type MockDomainEventHandlers_OnPostReadied_Call struct {
	*mock.Call
}

// OnPostReadied is a helper method to define mock.On call
//   - ctx context.Context
//   - event ddd.Event
func (_e *MockDomainEventHandlers_Expecter) OnPostReadied(ctx interface{}, event interface{}) *MockDomainEventHandlers_OnPostReadied_Call {
	return &MockDomainEventHandlers_OnPostReadied_Call{Call: _e.mock.On("OnPostReadied", ctx, event)}
}

func (_c *MockDomainEventHandlers_OnPostReadied_Call) Run(run func(ctx context.Context, event ddd.Event)) *MockDomainEventHandlers_OnPostReadied_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ddd.Event
		if args[1] != nil {
			arg1 = args[1].(ddd.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainEventHandlers_OnPostReadied_Call) Return(err error) *MockDomainEventHandlers_OnPostReadied_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainEventHandlers_OnPostReadied_Call) RunAndReturn(run func(ctx context.Context, event ddd.Event) error) *MockDomainEventHandlers_OnPostReadied_Call {
	_c.Call.Return(run)
	return _c
}
