// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationAdapter creates a new instance of MockNotificationAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationAdapter {
	mock := &MockNotificationAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationAdapter is an autogenerated mock type for the NotificationAdapter type
type MockNotificationAdapter struct {
	mock.Mock
}

type MockNotificationAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationAdapter) EXPECT() *MockNotificationAdapter_Expecter {
	return &MockNotificationAdapter_Expecter{mock: &_m.Mock}
}

// NotifyPostCanceled provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyPostCanceled(ctx context.Context, postID string, UserID string) error {
	ret := _mock.Called(ctx, postID, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPostCanceled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, postID, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyPostCanceled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPostCanceled'
type MockNotificationAdapter_NotifyPostCanceled_Call struct {
	*mock.Call
}

// NotifyPostCanceled is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyPostCanceled(ctx interface{}, postID interface{}, UserID interface{}) *MockNotificationAdapter_NotifyPostCanceled_Call {
	return &MockNotificationAdapter_NotifyPostCanceled_Call{Call: _e.mock.On("NotifyPostCanceled", ctx, postID, UserID)}
}

func (_c *MockNotificationAdapter_NotifyPostCanceled_Call) Run(run func(ctx context.Context, postID string, UserID string)) *MockNotificationAdapter_NotifyPostCanceled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostCanceled_Call) Return(err error) *MockNotificationAdapter_NotifyPostCanceled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostCanceled_Call) RunAndReturn(run func(ctx context.Context, postID string, UserID string) error) *MockNotificationAdapter_NotifyPostCanceled_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyPostCreated provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyPostCreated(ctx context.Context, postID string, UserID string) error {
	ret := _mock.Called(ctx, postID, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPostCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, postID, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyPostCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPostCreated'
type MockNotificationAdapter_NotifyPostCreated_Call struct {
	*mock.Call
}

// NotifyPostCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyPostCreated(ctx interface{}, postID interface{}, UserID interface{}) *MockNotificationAdapter_NotifyPostCreated_Call {
	return &MockNotificationAdapter_NotifyPostCreated_Call{Call: _e.mock.On("NotifyPostCreated", ctx, postID, UserID)}
}

func (_c *MockNotificationAdapter_NotifyPostCreated_Call) Run(run func(ctx context.Context, postID string, UserID string)) *MockNotificationAdapter_NotifyPostCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostCreated_Call) Return(err error) *MockNotificationAdapter_NotifyPostCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostCreated_Call) RunAndReturn(run func(ctx context.Context, postID string, UserID string) error) *MockNotificationAdapter_NotifyPostCreated_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyPostReady provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyPostReady(ctx context.Context, postID string, UserID string) error {
	ret := _mock.Called(ctx, postID, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPostReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, postID, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyPostReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPostReady'
type MockNotificationAdapter_NotifyPostReady_Call struct {
	*mock.Call
}

// NotifyPostReady is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyPostReady(ctx interface{}, postID interface{}, UserID interface{}) *MockNotificationAdapter_NotifyPostReady_Call {
	return &MockNotificationAdapter_NotifyPostReady_Call{Call: _e.mock.On("NotifyPostReady", ctx, postID, UserID)}
}

func (_c *MockNotificationAdapter_NotifyPostReady_Call) Run(run func(ctx context.Context, postID string, UserID string)) *MockNotificationAdapter_NotifyPostReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostReady_Call) Return(err error) *MockNotificationAdapter_NotifyPostReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyPostReady_Call) RunAndReturn(run func(ctx context.Context, postID string, UserID string) error) *MockNotificationAdapter_NotifyPostReady_Call {
	_c.Call.Return(run)
	return _c
}
