// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/racibaz/go-arch/internal/modules/shared/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockEventRepository_Expecter) Delete(id interface{}) *MockEventRepository_Delete_Call {
	return &MockEventRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockEventRepository_Delete_Call) Run(run func(id string)) *MockEventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Delete_Call) Return(err error) *MockEventRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Delete_Call) RunAndReturn(run func(id string) error) *MockEventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) GetByID(id string) (*domain.Event, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.Event, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.Event); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id string
func (_e *MockEventRepository_Expecter) GetByID(id interface{}) *MockEventRepository_GetByID_Call {
	return &MockEventRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockEventRepository_GetByID_Call) Run(run func(id string)) *MockEventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_GetByID_Call) Return(event *domain.Event, err error) *MockEventRepository_GetByID_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_GetByID_Call) RunAndReturn(run func(id string) (*domain.Event, error)) *MockEventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) IsExists(title string, description string) (bool, error) {
	ret := _mock.Called(title, description)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(title, description)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(title, description)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(title, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type MockEventRepository_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - title string
//   - description string
func (_e *MockEventRepository_Expecter) IsExists(title interface{}, description interface{}) *MockEventRepository_IsExists_Call {
	return &MockEventRepository_IsExists_Call{Call: _e.mock.On("IsExists", title, description)}
}

func (_c *MockEventRepository_IsExists_Call) Run(run func(title string, description string)) *MockEventRepository_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_IsExists_Call) Return(b bool, err error) *MockEventRepository_IsExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEventRepository_IsExists_Call) RunAndReturn(run func(title string, description string) (bool, error)) *MockEventRepository_IsExists_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) List() ([]*domain.Event, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*domain.Event, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*domain.Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockEventRepository_Expecter) List() *MockEventRepository_List_Call {
	return &MockEventRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockEventRepository_List_Call) Run(run func()) *MockEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventRepository_List_Call) Return(events []*domain.Event, err error) *MockEventRepository_List_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_List_Call) RunAndReturn(run func() ([]*domain.Event, error)) *MockEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Save(post *domain.Event) error {
	ret := _mock.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Event) error); ok {
		r0 = returnFunc(post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockEventRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - post *domain.Event
func (_e *MockEventRepository_Expecter) Save(post interface{}) *MockEventRepository_Save_Call {
	return &MockEventRepository_Save_Call{Call: _e.mock.On("Save", post)}
}

func (_c *MockEventRepository_Save_Call) Run(run func(post *domain.Event)) *MockEventRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Event
		if args[0] != nil {
			arg0 = args[0].(*domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Save_Call) Return(err error) *MockEventRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Save_Call) RunAndReturn(run func(post *domain.Event) error) *MockEventRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Update(post *domain.Event) error {
	ret := _mock.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Event) error); ok {
		r0 = returnFunc(post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEventRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - post *domain.Event
func (_e *MockEventRepository_Expecter) Update(post interface{}) *MockEventRepository_Update_Call {
	return &MockEventRepository_Update_Call{Call: _e.mock.On("Update", post)}
}

func (_c *MockEventRepository_Update_Call) Run(run func(post *domain.Event)) *MockEventRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Event
		if args[0] != nil {
			arg0 = args[0].(*domain.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Update_Call) Return(err error) *MockEventRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Update_Call) RunAndReturn(run func(post *domain.Event) error) *MockEventRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
