// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationAdapter creates a new instance of MockNotificationAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationAdapter {
	mock := &MockNotificationAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationAdapter is an autogenerated mock type for the NotificationAdapter type
type MockNotificationAdapter struct {
	mock.Mock
}

type MockNotificationAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationAdapter) EXPECT() *MockNotificationAdapter_Expecter {
	return &MockNotificationAdapter_Expecter{mock: &_m.Mock}
}

// NotifyUserCanceled provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyUserCanceled(ctx context.Context, UserID string) error {
	ret := _mock.Called(ctx, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserCanceled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyUserCanceled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserCanceled'
type MockNotificationAdapter_NotifyUserCanceled_Call struct {
	*mock.Call
}

// NotifyUserCanceled is a helper method to define mock.On call
//   - ctx context.Context
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyUserCanceled(ctx interface{}, UserID interface{}) *MockNotificationAdapter_NotifyUserCanceled_Call {
	return &MockNotificationAdapter_NotifyUserCanceled_Call{Call: _e.mock.On("NotifyUserCanceled", ctx, UserID)}
}

func (_c *MockNotificationAdapter_NotifyUserCanceled_Call) Run(run func(ctx context.Context, UserID string)) *MockNotificationAdapter_NotifyUserCanceled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserCanceled_Call) Return(err error) *MockNotificationAdapter_NotifyUserCanceled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserCanceled_Call) RunAndReturn(run func(ctx context.Context, UserID string) error) *MockNotificationAdapter_NotifyUserCanceled_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyUserReady provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyUserReady(ctx context.Context, UserID string) error {
	ret := _mock.Called(ctx, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyUserReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserReady'
type MockNotificationAdapter_NotifyUserReady_Call struct {
	*mock.Call
}

// NotifyUserReady is a helper method to define mock.On call
//   - ctx context.Context
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyUserReady(ctx interface{}, UserID interface{}) *MockNotificationAdapter_NotifyUserReady_Call {
	return &MockNotificationAdapter_NotifyUserReady_Call{Call: _e.mock.On("NotifyUserReady", ctx, UserID)}
}

func (_c *MockNotificationAdapter_NotifyUserReady_Call) Run(run func(ctx context.Context, UserID string)) *MockNotificationAdapter_NotifyUserReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserReady_Call) Return(err error) *MockNotificationAdapter_NotifyUserReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserReady_Call) RunAndReturn(run func(ctx context.Context, UserID string) error) *MockNotificationAdapter_NotifyUserReady_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyUserRegistered provides a mock function for the type MockNotificationAdapter
func (_mock *MockNotificationAdapter) NotifyUserRegistered(ctx context.Context, UserID string) error {
	ret := _mock.Called(ctx, UserID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyUserRegistered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, UserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationAdapter_NotifyUserRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyUserRegistered'
type MockNotificationAdapter_NotifyUserRegistered_Call struct {
	*mock.Call
}

// NotifyUserRegistered is a helper method to define mock.On call
//   - ctx context.Context
//   - UserID string
func (_e *MockNotificationAdapter_Expecter) NotifyUserRegistered(ctx interface{}, UserID interface{}) *MockNotificationAdapter_NotifyUserRegistered_Call {
	return &MockNotificationAdapter_NotifyUserRegistered_Call{Call: _e.mock.On("NotifyUserRegistered", ctx, UserID)}
}

func (_c *MockNotificationAdapter_NotifyUserRegistered_Call) Run(run func(ctx context.Context, UserID string)) *MockNotificationAdapter_NotifyUserRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserRegistered_Call) Return(err error) *MockNotificationAdapter_NotifyUserRegistered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationAdapter_NotifyUserRegistered_Call) RunAndReturn(run func(ctx context.Context, UserID string) error) *MockNotificationAdapter_NotifyUserRegistered_Call {
	_c.Call.Return(run)
	return _c
}
