// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/racibaz/go-arch/internal/modules/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DeleteMobileUserRefreshToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteMobileUserRefreshToken(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMobileUserRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteMobileUserRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMobileUserRefreshToken'
type MockUserRepository_DeleteMobileUserRefreshToken_Call struct {
	*mock.Call
}

// DeleteMobileUserRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) DeleteMobileUserRefreshToken(ctx interface{}, id interface{}) *MockUserRepository_DeleteMobileUserRefreshToken_Call {
	return &MockUserRepository_DeleteMobileUserRefreshToken_Call{Call: _e.mock.On("DeleteMobileUserRefreshToken", ctx, id)}
}

func (_c *MockUserRepository_DeleteMobileUserRefreshToken_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_DeleteMobileUserRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteMobileUserRefreshToken_Call) Return(err error) *MockUserRepository_DeleteMobileUserRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteMobileUserRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserRepository_DeleteMobileUserRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebUserRefreshToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteWebUserRefreshToken(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebUserRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteWebUserRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebUserRefreshToken'
type MockUserRepository_DeleteWebUserRefreshToken_Call struct {
	*mock.Call
}

// DeleteWebUserRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) DeleteWebUserRefreshToken(ctx interface{}, id interface{}) *MockUserRepository_DeleteWebUserRefreshToken_Call {
	return &MockUserRepository_DeleteWebUserRefreshToken_Call{Call: _e.mock.On("DeleteWebUserRefreshToken", ctx, id)}
}

func (_c *MockUserRepository_DeleteWebUserRefreshToken_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_DeleteWebUserRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteWebUserRefreshToken_Call) Return(err error) *MockUserRepository_DeleteWebUserRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteWebUserRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserRepository_DeleteWebUserRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user *domain.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user *domain.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByRefreshTokenAtMobile provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByRefreshTokenAtMobile(ctx context.Context, refreshToken string) (*domain.User, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByRefreshTokenAtMobile")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByRefreshTokenAtMobile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByRefreshTokenAtMobile'
type MockUserRepository_GetUserByRefreshTokenAtMobile_Call struct {
	*mock.Call
}

// GetUserByRefreshTokenAtMobile is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockUserRepository_Expecter) GetUserByRefreshTokenAtMobile(ctx interface{}, refreshToken interface{}) *MockUserRepository_GetUserByRefreshTokenAtMobile_Call {
	return &MockUserRepository_GetUserByRefreshTokenAtMobile_Call{Call: _e.mock.On("GetUserByRefreshTokenAtMobile", ctx, refreshToken)}
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtMobile_Call) Run(run func(ctx context.Context, refreshToken string)) *MockUserRepository_GetUserByRefreshTokenAtMobile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtMobile_Call) Return(user *domain.User, err error) *MockUserRepository_GetUserByRefreshTokenAtMobile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtMobile_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.User, error)) *MockUserRepository_GetUserByRefreshTokenAtMobile_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByRefreshTokenAtWeb provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByRefreshTokenAtWeb(ctx context.Context, refreshToken string) (*domain.User, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByRefreshTokenAtWeb")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByRefreshTokenAtWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByRefreshTokenAtWeb'
type MockUserRepository_GetUserByRefreshTokenAtWeb_Call struct {
	*mock.Call
}

// GetUserByRefreshTokenAtWeb is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockUserRepository_Expecter) GetUserByRefreshTokenAtWeb(ctx interface{}, refreshToken interface{}) *MockUserRepository_GetUserByRefreshTokenAtWeb_Call {
	return &MockUserRepository_GetUserByRefreshTokenAtWeb_Call{Call: _e.mock.On("GetUserByRefreshTokenAtWeb", ctx, refreshToken)}
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtWeb_Call) Run(run func(ctx context.Context, refreshToken string)) *MockUserRepository_GetUserByRefreshTokenAtWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtWeb_Call) Return(user *domain.User, err error) *MockUserRepository_GetUserByRefreshTokenAtWeb_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByRefreshTokenAtWeb_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.User, error)) *MockUserRepository_GetUserByRefreshTokenAtWeb_Call {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) IsExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type MockUserRepository_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) IsExists(ctx interface{}, email interface{}) *MockUserRepository_IsExists_Call {
	return &MockUserRepository_IsExists_Call{Call: _e.mock.On("IsExists", ctx, email)}
}

func (_c *MockUserRepository_IsExists_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_IsExists_Call) Return(b bool, err error) *MockUserRepository_IsExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_IsExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserRepository_IsExists_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Me(ctx context.Context, refreshToken string) (*domain.User, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type MockUserRepository_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockUserRepository_Expecter) Me(ctx interface{}, refreshToken interface{}) *MockUserRepository_Me_Call {
	return &MockUserRepository_Me_Call{Call: _e.mock.On("Me", ctx, refreshToken)}
}

func (_c *MockUserRepository_Me_Call) Run(run func(ctx context.Context, refreshToken string)) *MockUserRepository_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Me_Call) Return(user *domain.User, err error) *MockUserRepository_Me_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Me_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.User, error)) *MockUserRepository_Me_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Register(ctx context.Context, user *domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockUserRepository_Expecter) Register(ctx interface{}, user interface{}) *MockUserRepository_Register_Call {
	return &MockUserRepository_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *MockUserRepository_Register_Call) Run(run func(ctx context.Context, user *domain.User)) *MockUserRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Register_Call) Return(err error) *MockUserRepository_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Register_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) error) *MockUserRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMobileUserRefreshToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateMobileUserRefreshToken(ctx context.Context, id string, refreshToken string) error {
	ret := _mock.Called(ctx, id, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMobileUserRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateMobileUserRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMobileUserRefreshToken'
type MockUserRepository_UpdateMobileUserRefreshToken_Call struct {
	*mock.Call
}

// UpdateMobileUserRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - refreshToken string
func (_e *MockUserRepository_Expecter) UpdateMobileUserRefreshToken(ctx interface{}, id interface{}, refreshToken interface{}) *MockUserRepository_UpdateMobileUserRefreshToken_Call {
	return &MockUserRepository_UpdateMobileUserRefreshToken_Call{Call: _e.mock.On("UpdateMobileUserRefreshToken", ctx, id, refreshToken)}
}

func (_c *MockUserRepository_UpdateMobileUserRefreshToken_Call) Run(run func(ctx context.Context, id string, refreshToken string)) *MockUserRepository_UpdateMobileUserRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateMobileUserRefreshToken_Call) Return(err error) *MockUserRepository_UpdateMobileUserRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateMobileUserRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id string, refreshToken string) error) *MockUserRepository_UpdateMobileUserRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWebUserRefreshToken provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateWebUserRefreshToken(ctx context.Context, id string, refreshToken string) error {
	ret := _mock.Called(ctx, id, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWebUserRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateWebUserRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWebUserRefreshToken'
type MockUserRepository_UpdateWebUserRefreshToken_Call struct {
	*mock.Call
}

// UpdateWebUserRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - refreshToken string
func (_e *MockUserRepository_Expecter) UpdateWebUserRefreshToken(ctx interface{}, id interface{}, refreshToken interface{}) *MockUserRepository_UpdateWebUserRefreshToken_Call {
	return &MockUserRepository_UpdateWebUserRefreshToken_Call{Call: _e.mock.On("UpdateWebUserRefreshToken", ctx, id, refreshToken)}
}

func (_c *MockUserRepository_UpdateWebUserRefreshToken_Call) Run(run func(ctx context.Context, id string, refreshToken string)) *MockUserRepository_UpdateWebUserRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateWebUserRefreshToken_Call) Return(err error) *MockUserRepository_UpdateWebUserRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateWebUserRefreshToken_Call) RunAndReturn(run func(ctx context.Context, id string, refreshToken string) error) *MockUserRepository_UpdateWebUserRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
