apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-arch
  template:
    metadata:
      labels:
        app: go-arch
    spec:
      containers:
        - name: go-arch
          image: go-arch:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: PORT
              value: "8080"
