// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/racibaz/go-arch/internal/modules/post/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetPostService creates a new instance of MockGetPostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPostService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPostService {
	mock := &MockGetPostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetPostService is an autogenerated mock type for the GetPostService type
type MockGetPostService struct {
	mock.Mock
}

type MockGetPostService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPostService) EXPECT() *MockGetPostService_Expecter {
	return &MockGetPostService_Expecter{mock: &_m.Mock}
}

// GetPostByID provides a mock function for the type MockGetPostService
func (_mock *MockGetPostService) GetPostByID(ctx context.Context, id string) (*domain.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPostByID")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetPostService_GetPostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostByID'
type MockGetPostService_GetPostByID_Call struct {
	*mock.Call
}

// GetPostByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGetPostService_Expecter) GetPostByID(ctx interface{}, id interface{}) *MockGetPostService_GetPostByID_Call {
	return &MockGetPostService_GetPostByID_Call{Call: _e.mock.On("GetPostByID", ctx, id)}
}

func (_c *MockGetPostService_GetPostByID_Call) Run(run func(ctx context.Context, id string)) *MockGetPostService_GetPostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetPostService_GetPostByID_Call) Return(post *domain.Post, err error) *MockGetPostService_GetPostByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockGetPostService_GetPostByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Post, error)) *MockGetPostService_GetPostByID_Call {
	_c.Call.Return(run)
	return _c
}
