// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"
	"github.com/racibaz/go-arch/internal/modules/post/application/command"

	"github.com/racibaz/go-arch/internal/modules/post/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostService creates a new instance of MockPostService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostService {
	mock := &MockPostService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostService is an autogenerated mock type for the PostService type
type MockPostService struct {
	mock.Mock
}

type MockPostService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostService) EXPECT() *MockPostService_Expecter {
	return &MockPostService_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type MockPostService
func (_mock *MockPostService) Handle(ctx context.Context, postDto command.CreatePostCommand) error {
	ret := _mock.Called(ctx, postDto)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.CreatePostCommand) error); ok {
		r0 = returnFunc(ctx, postDto)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostService_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockPostService_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - postDto dto.CreatePostCommand
func (_e *MockPostService_Expecter) CreatePost(ctx interface{}, postDto interface{}) *MockPostService_CreatePost_Call {
	return &MockPostService_CreatePost_Call{Call: _e.mock.On("Handle", ctx, postDto)}
}

func (_c *MockPostService_CreatePost_Call) Run(run func(ctx context.Context, postDto command.CreatePostCommand)) *MockPostService_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.CreatePostCommand
		if args[1] != nil {
			arg1 = args[1].(command.CreatePostCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostService_CreatePost_Call) Return(err error) *MockPostService_CreatePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostService_CreatePost_Call) RunAndReturn(run func(ctx context.Context, postDto command.CreatePostCommand) error) *MockPostService_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockPostService
func (_mock *MockPostService) GetById(ctx context.Context, id string) (*domain.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockPostService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPostService_Expecter) GetById(ctx interface{}, id interface{}) *MockPostService_GetById_Call {
	return &MockPostService_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockPostService_GetById_Call) Run(run func(ctx context.Context, id string)) *MockPostService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostService_GetById_Call) Return(post *domain.Post, err error) *MockPostService_GetById_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostService_GetById_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Post, error)) *MockPostService_GetById_Call {
	_c.Call.Return(run)
	return _c
}
