definitions:
  domain.Post:
    properties:
      content:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/value_objects.PostStatus'
      title:
        type: string
      updatedAt:
        type: string
    type: object
  request_dtos.CreatePostRequestDto:
    description: CreatePostRequestDto is a data transfer object for creating a post
    properties:
      content:
        description: '@Description Content is the content of the post'
        type: string
      description:
        description: '@Description Description is the description of the post'
        type: string
      title:
        description: '@Description Title is the title of the post'
        type: string
    type: object
  value_objects.PostStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - PostStatusDraft
    - PostStatusPublished
    - PostStatusArchived
info:
  contact: {}
paths:
  /posts:
    post:
      consumes:
      - application/json
      description: It is a method to create a new post
      parameters:
      - description: Create Post Request DTO
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/request_dtos.CreatePostRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Post created successfully
          schema:
            $ref: '#/definitions/domain.Post'
      summary: post store
      tags:
      - posts
  /posts/{id}:
    get:
      consumes:
      - application/json
      description: It is a method to retrieve a post by its ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Post retrieved successfully
          schema:
            $ref: '#/definitions/domain.Post'
      summary: Get post by id
      tags:
      - posts
swagger: "2.0"
